package com.example.tuniscamp.entities;

public enum EventCategory {

    CAMPING_WITH_DIRECT_ACCESS_TO_THE_BEACH,
    CAMPING_WITH_HEATED_SWIMMING_POOL,
    CAMPING_WITH_INDOOR_SWIMMING_POOL,
    WELL_BEING_CAMPING_BALNEAOTHERAPY_HAMMAM_SAUNA,
    CAMPING_EQUIPPED_WITH_CHILDRENS_MIN_CLUBS,
    CAMPING_EQUIPPED_WITH_WATER_PARKS,
    CAMPING_WITH_UNUSUAL_ACCOMMODATION,
    LIVELIEST_CAMPING,
    CAMPING_AROUND_LAKES_AND_RIVERS,
    SPORTY,
    ECO_FRIENDLY_CAMPING,
    CAMPING_OFFERING_LUXURY_RENTALS,
    CAMPING_OPEN_YEAR_ROUND,
    YOUR_SECOND_HOME_ON_THE_CAMPING

}
